[package]
name = "benches"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
tokio = { version = "0.1.22", path = "../tokio", features = ["default"] }
bencher = "0.1.5"

[[bench]]
name = "fs"
path = "fs.rs"
harness = false
